In [ ]:
# of session completion given context and template choice. We then use 
# this model as a greedy policy to select the template with highest 
# predicted reward from the eligible pool. Since we only observe 
# rewards for the logged template, we evaluate the new policy using 
# inverse propensity scoring (IPS), assuming the logging policy was 
# uniform random within pools.

import polars as pl
import numpy as np

In [ ]:
TRAIN_PATH = "train_rsample_100k.parquet"  # your good sample
VAL_PATH   = "val_rsample_100k.parquet"

train = pl.read_parquet(TRAIN_PATH)
val   = pl.read_parquet(VAL_PATH)

print("Train:", train.shape)
print("Val:", val.shape)
print("Train baseline:", train.select(pl.mean("session_end_completed")).item())
print("Val baseline:", val.select(pl.mean("session_end_completed")).item())

Train: (100000, 10)
Val: (100000, 10)
Train baseline: 0.14704
Val baseline: 0.13557

In [ ]:
train.head(10)

shape: (10, 10)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ datetime ┆ ui_langua ┆ selected_ ┆ eligible_ ┆ … ┆ n_eligibl ┆ time_of_d ┆ session_e ┆ hour_utc  │
│ ---      ┆ ge        ┆ template  ┆ templates ┆   ┆ e         ┆ ay        ┆ nd_comple ┆ ---       │
│ f64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ted       ┆ f64       │
│          ┆ str       ┆ str       ┆ list[str] ┆   ┆ u32       ┆ f64       ┆ ---       ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ bool      ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 9.28338  ┆ fr        ┆ L         ┆ ["K",     ┆ … ┆ 9         ┆ 9.28338   ┆ false     ┆ 6.801111  │
│          ┆           ┆           ┆ "H", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
│ 9.623044 ┆ es        ┆ D         ┆ ["K",     ┆ … ┆ 9         ┆ 9.623044  ┆ false     ┆ 14.953056 │
│          ┆           ┆           ┆ "H", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
│ 5.172986 ┆ de        ┆ K         ┆ ["G",     ┆ … ┆ 10        ┆ 5.172986  ┆ false     ┆ 4.151667  │
│          ┆           ┆           ┆ "E", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
│ 6.269595 ┆ en        ┆ G         ┆ ["G",     ┆ … ┆ 9         ┆ 6.269595  ┆ false     ┆ 6.470278  │
│          ┆           ┆           ┆ "E", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
│ 0.913009 ┆ es        ┆ L         ┆ ["G",     ┆ … ┆ 9         ┆ 0.913009  ┆ false     ┆ 21.912222 │
│          ┆           ┆           ┆ "E", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
│ 0.636458 ┆ es        ┆ D         ┆ ["G",     ┆ … ┆ 10        ┆ 0.636458  ┆ false     ┆ 15.275    │
│          ┆           ┆           ┆ "E", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
│ 9.939329 ┆ es        ┆ F         ┆ ["K",     ┆ … ┆ 10        ┆ 9.939329  ┆ false     ┆ 22.543889 │
│          ┆           ┆           ┆ "H", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "A"]      ┆   ┆           ┆           ┆           ┆           │
│ 5.212697 ┆ en        ┆ E         ┆ ["G",     ┆ … ┆ 9         ┆ 5.212697  ┆ false     ┆ 5.104722  │
│          ┆           ┆           ┆ "E", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
│ 5.104537 ┆ fr        ┆ A         ┆ ["G",     ┆ … ┆ 10        ┆ 5.104537  ┆ false     ┆ 2.508889  │
│          ┆           ┆           ┆ "E", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
│ 4.63978  ┆ en        ┆ E         ┆ ["G",     ┆ … ┆ 10        ┆ 4.63978   ┆ false     ┆ 15.354722 │
│          ┆           ┆           ┆ "E", …    ┆   ┆           ┆           ┆           ┆           │
│          ┆           ┆           ┆ "D"]      ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
train = train.with_columns(
    ((pl.col("datetime") % 1) * 24)
        .floor()
        .cast(pl.Int8)
        .alias("hour_utc")
)

val = val.with_columns(
    ((pl.col("datetime") % 1) * 24)
        .floor()
        .cast(pl.Int8)
        .alias("hour_utc")
)

In [ ]:
#! Don't forget to drop one for Logistic regression (perfect multicollinearity)

In [ ]:
train.select("ui_language").unique()

shape: (23, 1)
┌─────────────┐
│ ui_language │
│ ---         │
│ str         │
╞═════════════╡
│ pl          │
│ zs          │
│ el          │
│ ja          │
│ es          │
│ …           │
│ tr          │
│ ko          │
│ hu          │
│ ar          │
│ ro          │
└─────────────┘

In [ ]:
val.select("ui_language").unique()

shape: (23, 1)
┌─────────────┐
│ ui_language │
│ ---         │
│ str         │
╞═════════════╡
│ ro          │
│ zs          │
│ hi          │
│ pl          │
│ dn          │
│ …           │
│ ko          │
│ hu          │
│ el          │
│ ru          │
│ id          │
└─────────────┘

In [ ]:
train = train.to_dummies(columns=["ui_language"])
val   = val.to_dummies(columns=["ui_language"])

In [ ]:
print(len(train.columns))
train.head(10)

32

shape: (10, 32)
┌──────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ datetime ┆ ui_languag ┆ ui_langua ┆ ui_langua ┆ … ┆ n_eligibl ┆ time_of_d ┆ session_e ┆ hour_utc │
│ ---      ┆ e_ar       ┆ ge_cs     ┆ ge_de     ┆   ┆ e         ┆ ay        ┆ nd_comple ┆ ---      │
│ f64      ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ted       ┆ i8       │
│          ┆ u8         ┆ u8        ┆ u8        ┆   ┆ u32       ┆ f64       ┆ ---       ┆          │
│          ┆            ┆           ┆           ┆   ┆           ┆           ┆ bool      ┆          │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 9.28338  ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 9         ┆ 9.28338   ┆ false     ┆ 6        │
│ 9.623044 ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 9         ┆ 9.623044  ┆ false     ┆ 14       │
│ 5.172986 ┆ 0          ┆ 0         ┆ 1         ┆ … ┆ 10        ┆ 5.172986  ┆ false     ┆ 4        │
│ 6.269595 ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 9         ┆ 6.269595  ┆ false     ┆ 6        │
│ 0.913009 ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 9         ┆ 0.913009  ┆ false     ┆ 21       │
│ 0.636458 ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 10        ┆ 0.636458  ┆ false     ┆ 15       │
│ 9.939329 ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 10        ┆ 9.939329  ┆ false     ┆ 22       │
│ 5.212697 ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 9         ┆ 5.212697  ┆ false     ┆ 5        │
│ 5.104537 ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 10        ┆ 5.104537  ┆ false     ┆ 2        │
│ 4.63978  ┆ 0          ┆ 0         ┆ 0         ┆ … ┆ 10        ┆ 4.63978   ┆ false     ┆ 15       │
└──────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [ ]:
# same order in both val and train
set(train.columns) == set(val.columns)

assert train.columns == val.columns



## To drop for modeling: history

## history_length: number of past exposures
## n_eligible: number of templates a user is able to receive at the moment

## Add from history: length between template sent

In [ ]:
#                       their most recent notification (any template).


train = train.with_columns(
    pl.col("history").map_elements(
        lambda hist: 100.0 if (hist is None or len(hist) == 0)
        else float(min(item["n_days"] for item in hist)),
        return_dtype=pl.Float64
    ).alias("time_since_last_notification_days")
)

val = val.with_columns(
    pl.col("history").map_elements(
        lambda hist: 100.0 if (hist is None or len(hist) == 0)
        else float(min(item["n_days"] for item in hist)),
        return_dtype=pl.Float64
    ).alias("time_since_last_notification_days")
)

In [ ]:
from collections import Counter

train = train.with_columns(
    pl.col("history").map_elements(
        lambda hist: 0 if (hist is None or len(hist) == 0)
        else max(
            Counter(
                # take 5 most recent by smallest n_days
                [item["template"] for item in sorted(hist, key=lambda d: d["n_days"])[:5]]
            ).values()
        ),
        return_dtype=pl.Int16
    ).alias("max_template_count_last_5")
)

val = val.with_columns(
    pl.col("history").map_elements(
        lambda hist: 0 if (hist is None or len(hist) == 0)
        else max(
            Counter(
                [item["template"] for item in sorted(hist, key=lambda d: d["n_days"])[:5]]
            ).values()
        ),
        return_dtype=pl.Int16
    ).alias("max_template_count_last_5")
)

In [ ]:
## Add day index 
train = train.with_columns(
    (pl.col("datetime").floor().cast(pl.Int32) + 1).alias("day_index")
)

val = val.with_columns(
    (pl.col("datetime").floor().cast(pl.Int32) + 1).alias("day_index")
)

In [ ]:
train = train.drop(["history"])
val   = val.drop(["history"])

In [ ]:
OUT_TRAIN = "train_preprocessed_100k.parquet"
OUT_VAL   = "val_preprocessed_100k.parquet"

train.write_parquet(OUT_TRAIN)
val.write_parquet(OUT_VAL)

print("Wrote:", OUT_TRAIN, OUT_VAL)

Wrote: train_preprocessed_100k.parquet val_preprocessed_100k.parquet